# designed by mew
# Generated by Django 5.2.17 on 2026-09-22 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import cms.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("publication", "论文与专利"),
                            ("person", "成员与校友"),
                            ("group", "成员分组"),
                            ("photo", "照片与相册"),
                            ("project", "研究项目"),
                            ("news", "新闻动态"),
                            ("direction", "研究方向"),
                            ("venue", "会议期刊目录"),
                            ("page", "页面内容"),
                            ("navigation", "导航与页脚链接"),
                            ("section", "首页栏目编排"),
                            ("site", "站点与联系信息"),
                            ("home", "首页与轮播设置"),
                            ("text", "界面中英文文案"),
                        ],
                        db_index=True,
                        max_length=24,
                        verbose_name="内容类型",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default=cms.models.new_key, max_length=100, verbose_name="稳定编号"
                    ),
                ),
                ("payload", models.JSONField(default=dict, verbose_name="编辑稿")),
                ("live", models.JSONField(blank=True, null=True, verbose_name="已发布快照")),
                (
                    "sort_order",
                    models.IntegerField(
                        default=100,
                        help_text="数字越小越靠前；新闻和论文先按日期/年份排列。",
                        verbose_name="显示顺序",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_deleted", models.BooleanField(default=False, verbose_name="在回收站")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="最后修改")),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="发布时间"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "内容条目",
                "verbose_name_plural": "全部内容",
                "ordering": ["sort_order", "-updated_at"],
                "permissions": [
                    ("publish_content", "发布、下线和回收内容"),
                    ("import_content", "导入内容备份"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Direction",
            fields=[],
            options={
                "verbose_name": "研究方向",
                "verbose_name_plural": "研究方向",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cms.contentitem",),
        ),
        migrations.CreateModel(
            name="Group",
            fields=[],
            options={
                "verbose_name": "成员分组",
                "verbose_name_plural": "成员分组",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cms.contentitem",),
        ),
        migrations.CreateModel(
            name="Home",
            fields=[],
            options={
                "verbose_name": "首页与轮播设置",
                "verbose_name_plural": "首页与轮播设置",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cms.contentitem",),
        ),
        migrations.CreateModel(
            name="Navigation",
            fields=[],
            options={
                "verbose_name": "导航与页脚链接",
                "verbose_name_plural": "导航与页脚链接",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cms.contentitem",),
        ),
        migrations.CreateModel(
            name="News",
            fields=[],
            options={
                "verbose_name": "新闻动态",
                "verbose_name_plural": "新闻动态",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cms.contentitem",),
        ),
        migrations.CreateModel(
            name="Page",
            fields=[],
            options={
                "verbose_name": "页面内容",
                "verbose_name_plural": "页面内容",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cms.contentitem",),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[],
            options={
                "verbose_name": "成员与校友",
                "verbose_name_plural": "成员与校友",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cms.contentitem",),
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[],
            options={
                "verbose_name": "照片与相册",
                "verbose_name_plural": "照片与相册",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cms.contentitem",),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[],
            options={
                "verbose_name": "研究项目",
                "verbose_name_plural": "研究项目",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cms.contentitem",),
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[],
            options={
                "verbose_name": "论文与专利",
                "verbose_name_plural": "论文与专利",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cms.contentitem",),
        ),
        migrations.CreateModel(
            name="Section",
            fields=[],
            options={
                "verbose_name": "首页栏目编排",
                "verbose_name_plural": "首页栏目编排",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cms.contentitem",),
        ),
        migrations.CreateModel(
            name="Site",
            fields=[],
            options={
                "verbose_name": "站点与联系信息",
                "verbose_name_plural": "站点与联系信息",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cms.contentitem",),
        ),
        migrations.CreateModel(
            name="Text",
            fields=[],
            options={
                "verbose_name": "界面中英文文案",
                "verbose_name_plural": "界面中英文文案",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cms.contentitem",),
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[],
            options={
                "verbose_name": "会议期刊目录",
                "verbose_name_plural": "会议期刊目录",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cms.contentitem",),
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="素材名称")),
                (
                    "file",
                    models.FileField(upload_to=cms.models.media_path, verbose_name="上传文件"),
                ),
                (
                    "alt_zh",
                    models.CharField(blank=True, max_length=300, verbose_name="图片说明（中文）"),
                ),
                (
                    "alt_en",
                    models.CharField(blank=True, max_length=300, verbose_name="图片说明（英文）"),
                ),
                (
                    "credit",
                    models.CharField(blank=True, max_length=300, verbose_name="来源 / 摄影者"),
                ),
                ("category", models.CharField(blank=True, max_length=100, verbose_name="分类")),
                ("mime_type", models.CharField(editable=False, max_length=100)),
                ("size", models.PositiveBigIntegerField(default=0, editable=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, verbose_name="上传时间")),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "素材",
                "verbose_name_plural": "素材库",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Revision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("snapshot", models.JSONField()),
                ("action", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="cms.contentitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="contentitem",
            constraint=models.UniqueConstraint(fields=("kind", "key"), name="unique_content_key"),
        ),
    ]
