// designed by mew
// Generated by scripts/generate_types.py. Edit backend/cms/schema.py instead.
export interface ContentLink {
  label: string;
  url: string;
}
export interface ContentRecord {
  id: string;
  order: number;
  aliases?: string[];
}
export interface Publication extends ContentRecord {
  title: string;
  authors: string;
  year: string;
  category:
    'Conference Papers' | 'Journal Papers' | 'Chinese Papers' | 'Preprints' | 'Granted Patents';
  venue_key: string;
  venueShort: string;
  venueFull: string;
  track:
    '' | 'Poster' | 'Demo' | 'Workshop' | 'Short Paper' | 'Work-in-Progress (WIP)' | 'Preprint';
  ccfRating: '' | 'A' | 'B' | 'C' | 'unranked';
  ccfEdition: string;
  ccfSource: string;
  ratingNote: string;
  doi: string;
  publishedDate: string;
  conferenceYear: string;
  volume: string;
  issue: string;
  pages: string;
  citation: string;
  abstract_zh: string;
  abstract_en: string;
  links: ContentLink[];
  image: string;
  imageCaption_zh: string;
  imageCaption_en: string;
}
export interface Person extends ContentRecord {
  name_zh: string;
  name_en: string;
  group: string;
  role_zh: string;
  role_en: string;
  bio_zh: string;
  bio_en: string;
  image: string;
  links: ContentLink[];
  placeholder: boolean;
}
export interface Group extends ContentRecord {
  title_zh: string;
  title_en: string;
  layout: 'cards' | 'faculty';
}
export interface Photo extends ContentRecord {
  title_zh: string;
  title_en: string;
  image: string;
  show_home: boolean;
  show_people: boolean;
}
export interface Project extends ContentRecord {
  slug: string;
  name_zh: string;
  name_en: string;
  category_zh: string;
  category_en: string;
  summary_zh: string;
  summary_en: string;
  body_zh: string;
  body_en: string;
  publications: string[];
  image: string;
  links: ContentLink[];
  seoDescription_zh: string;
  seoDescription_en: string;
}
export interface News extends ContentRecord {
  title_zh: string;
  title_en: string;
  date: string;
  category: 'Publication' | 'Award' | 'Lab update';
  image: string;
  links: ContentLink[];
}
export interface Direction extends ContentRecord {
  title_zh: string;
  title_en: string;
  description_zh: string;
  description_en: string;
  image: string;
  projects: string[];
  publications: string[];
}
export interface Venue extends ContentRecord {
  title: string;
  full: string;
  rating: 'A' | 'B' | 'C' | 'unranked';
  edition: string;
  note: string;
  source: string;
}
export interface Page extends ContentRecord {
  slug: string;
  title_zh: string;
  title_en: string;
  description_zh: string;
  description_en: string;
  image: string;
  body_zh: string;
  body_en: string;
  seoDescription_zh: string;
  seoDescription_en: string;
}
export interface Navigation extends ContentRecord {
  title_zh: string;
  title_en: string;
  url: string;
  header: boolean;
  footer: boolean;
  highlight: boolean;
}
export interface Section extends ContentRecord {
  component:
    'hero' | 'research' | 'projects' | 'publications' | 'people' | 'news' | 'join' | 'content';
  title_zh: string;
  title_en: string;
  body_zh: string;
  body_en: string;
  image: string;
}
export interface Site extends ContentRecord {
  name_zh: string;
  name_en: string;
  logo: string;
  favicon: string;
  email: string;
  address_zh: string;
  address_en: string;
  footer_zh: string;
  footer_en: string;
  university_url: string;
  university_zh: string;
  university_en: string;
  default_language: 'en' | 'zh';
  default_theme: 'light' | 'dark';
  enable_theme: boolean;
  seoDescription_zh: string;
  seoDescription_en: string;
}
export interface Home extends ContentRecord {
  title_zh: string;
  title_en: string;
  description_zh: string;
  description_en: string;
  eyebrow_zh: string;
  eyebrow_en: string;
  video: string;
  poster: string;
  overlay: number;
  featured_projects: string[];
  featured_publications: string[];
  news_limit: number;
  carousel_seconds: number;
  join_image: string;
  join_title_zh: string;
  join_title_en: string;
  join_description_zh: string;
  join_description_en: string;
}
export interface Text extends ContentRecord {
  source: string;
  value_zh: string;
  value_en: string;
}
export interface SiteContent {
  publication: Publication[];
  person: Person[];
  group: Group[];
  photo: Photo[];
  project: Project[];
  news: News[];
  direction: Direction[];
  venue: Venue[];
  page: Page[];
  navigation: Navigation[];
  section: Section[];
  site: Site[];
  home: Home[];
  text: Text[];
}
export type ContentKind = keyof SiteContent;
export interface SiteResponse {
  schemaVersion: number;
  preview: boolean;
  content: SiteContent;
}
