# designed by mew
"""Generate the API field types from the backend catalogue. Run after schema edits."""

import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location("schema", ROOT / "backend/cms/schema.py")
schema = importlib.util.module_from_spec(spec)
spec.loader.exec_module(schema)
lines = [
    "// designed by mew",
    "// Generated by scripts/generate_types.py. Edit backend/cms/schema.py instead.",
    "export interface ContentLink { label: string; url: string }",
    "export interface ContentRecord { id: string; order: number; aliases?: string[] }",
]
for kind, fields in schema.SCHEMAS.items():
    lines.append(f"export interface {kind.title()} extends ContentRecord {{")
    for field in fields:
        typ = field["type"]
        value = "string"
        if typ == "choice":
            value = " | ".join(repr(v) for v, _ in field["choices"])
        elif typ == "boolean":
            value = "boolean"
        elif typ == "integer":
            value = "number"
        elif typ == "links":
            value = "ContentLink[]"
        elif typ == "references":
            value = "string[]"
        optional = "?" if field.get("private") else ""
        lines.append(f"  {field['name']}{optional}: {value};")
    lines.append("}")
lines.append("export interface SiteContent {")
for kind in schema.SCHEMAS:
    lines.append(f"  {kind}: {kind.title()}[];")
lines.extend(
    [
        "}",
        "export type ContentKind = keyof SiteContent;",
        "export interface SiteResponse { schemaVersion: number; preview: boolean; content: SiteContent }",
    ]
)
(ROOT / "frontend/src/types/content.ts").write_text("\n".join(lines) + "\n")
